package com.xprod.xproddesktop;

import com.xprod.xproddesktop.dao.Connexion;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.print.PrintException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samir Ibrahim
 */
public class Commande extends javax.swing.JFrame {

    /**
     * Creates new form Commande
     */
    public Commande() {
        initComponents();
        setLocationRelativeTo(null);
        tableUpdateProduits();
        tableUpdateClients();
    }
    
    //Connexion
    Connexion cn = new Connexion();
    Connection con;
    PreparedStatement pst;
    
    
    private void tableUpdateProduits() {
        int cpt;
        
        try {
            
            con = cn.getCon();
            
            String query = "SELECT * FROM produit";
            pst = con.prepareStatement(query);
            
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            cpt = rsmd.getColumnCount();
           
            DefaultTableModel dtm = (DefaultTableModel) tableProduitCommande.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {
                Vector vect = new Vector();
                
                vect.add(rs.getString("idproduit"));
                vect.add(rs.getString("refproduit"));
                vect.add(rs.getString("designation"));
                vect.add(rs.getString("description"));
                vect.add(rs.getString("prixuht"));
                
                dtm.addRow(vect);
                
            }

        } catch (Exception e) {
        }
    }
    
     private void tableUpdateClients() {
        int cpt;
        
        try {
            
            con = cn.getCon();
            
            String query = "SELECT * FROM clients";
            pst = con.prepareStatement(query);
            
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            cpt = rsmd.getColumnCount();
           
            DefaultTableModel dtm = (DefaultTableModel) tableClients.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {
                Vector vect = new Vector();
                
                vect.add(rs.getString("IDCLIENT"));
                vect.add(rs.getString("PRENOM"));
                vect.add(rs.getString("NOM"));
                vect.add(rs.getString("ADRESSE"));
                vect.add(rs.getString("CP"));
                vect.add(rs.getString("VILLE"));
                vect.add(rs.getString("PAYS"));
                vect.add(rs.getString("TEL"));
                vect.add(rs.getString("EMAIL"));
                
                
                dtm.addRow(vect);
                
            }

        } catch (Exception e) {
        }
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduitCommande = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRefProduitCMD = new javax.swing.JTextField();
        txtDesignationProduitCMD = new javax.swing.JTextField();
        txtDescriptifProduitCMD = new javax.swing.JTextField();
        txtPrixUHTProduitCMD = new javax.swing.JTextField();
        txtQteProduitCMD = new javax.swing.JTextField();
        txtPrixTHTProduitCMD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPrenomCMD = new javax.swing.JTextField();
        txtNomCMD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCommande = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTVACMD = new javax.swing.JTextField();
        txtPrixTTCCMd = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCreateBill = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtFraisPort = new javax.swing.JTextField();
        btnPrintBill = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 176, 255));

        tableProduitCommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "REF", "DESIGNATION", "DESCRIPTIF", "PRIX UHT"
            }
        ));
        tableProduitCommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProduitCommandeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProduitCommande);

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "PRENOM", "ADRESSE", "CP", "VILLE", "PAYS", "TEL", "EMAIL"
            }
        ));
        jScrollPane2.setViewportView(tableClients);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Listes des Produits");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel4.setText("Liste des Clients");

        jLabel5.setText("REF :");

        jLabel6.setText("DESIGNATION :");

        jLabel7.setText("DESCRIPTIF :");

        jLabel8.setText("PRIX UHT :");

        jLabel9.setText("QTE :");

        jLabel10.setText("PRIX THT :");

        jLabel11.setText("PRENOM CLIENT :");

        jLabel12.setText("NOM CLIENT :");

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel13.setText("Ligne de Commande");

        tableCommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PRODUIT", "REF", "DESIGNATION", "DESCRIPTION", "PRIX UHT", "QTE", "PRIX THC"
            }
        ));
        jScrollPane3.setViewportView(tableCommande);

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel14.setText("Commande");

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel15.setText("Frais de port");

        txtBill.setColumns(20);
        txtBill.setRows(5);
        jScrollPane4.setViewportView(txtBill);

        jLabel16.setText("T.V.A :");

        jLabel17.setText("Prix TTC");

        txtPrixTTCCMd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrixTTCCMdActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jButton1.setText("Valider la commande");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Créer la facture");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCreateBill.setForeground(new java.awt.Color(1, 85, 147));
        btnCreateBill.setText("Créer la facture");
        btnCreateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBillActionPerformed(evt);
            }
        });

        jLabel18.setText("Frais de port :");

        btnPrintBill.setBackground(new java.awt.Color(0, 0, 0));
        btnPrintBill.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnPrintBill.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintBill.setText("Imprimer la facture");
        btnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(277, 277, 277))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDesignationProduitCMD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDescriptifProduitCMD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRefProduitCMD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCreateBill)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPrixUHTProduitCMD, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(txtQteProduitCMD)
                                            .addComponent(txtPrixTHTProduitCMD)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPrenomCMD, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(txtNomCMD)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnPrintBill)
                                    .addGap(57, 57, 57))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(jButton1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel16))
                                            .addGap(55, 55, 55)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPrixTTCCMd)
                                                .addComponent(txtTVACMD)))
                                        .addComponent(txtFraisPort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(153, 153, 153)))))
                        .addGap(35, 35, 35))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtRefProduitCMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtPrenomCMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtDesignationProduitCMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNomCMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDescriptifProduitCMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrixUHTProduitCMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtQteProduitCMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrixTHTProduitCMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(txtFraisPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(txtTVACMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtPrixTTCCMd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btnCreateBill)
                    .addComponent(btnPrintBill))
                .addGap(45, 45, 45))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nimbus Sans", 1, 24)); // NOI18N
        jLabel1.setText("Gestion des commandes");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/commande.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(562, 562, 562))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(220, 220, 220));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableProduitCommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProduitCommandeMouseClicked
        // Pour séléctionner les informations d'un champ
        double sum = 0.0;
        double totalTTC = 0.0;
        double prixTVA = 0.0;
        
        
        DefaultTableModel dtm = (DefaultTableModel) tableProduitCommande.getModel();

        int selectedIndex = tableProduitCommande.getSelectedRow();
        
        //Préremplir les champs de texte
        txtRefProduitCMD.setText(dtm.getValueAt(selectedIndex, 1).toString());
        txtDesignationProduitCMD.setText(dtm.getValueAt(selectedIndex, 2).toString());
        txtDescriptifProduitCMD.setText(dtm.getValueAt(selectedIndex, 3).toString());
        txtPrixUHTProduitCMD.setText(dtm.getValueAt(selectedIndex, 4).toString());
        
        //Ajout dans la table des commandes
        String idProduit = dtm.getValueAt(selectedIndex, 0).toString();
        String txtRefProduit = dtm.getValueAt(selectedIndex, 1).toString();
        String txtDesignationProduit = dtm.getValueAt(selectedIndex, 2).toString();
        String txtDescriptifProduit = dtm.getValueAt(selectedIndex, 3).toString();
        double txtPrixUHTProduit = Double.parseDouble(dtm.getValueAt(selectedIndex, 4).toString());
        int qte = Integer.parseInt(JOptionPane.showInputDialog(null, "Entrer la quantité :"));
        
        double tot = txtPrixUHTProduit * qte;
        double fraisPort = Double.parseDouble(JOptionPane.showInputDialog(null, "Entrer les frais de port !"));
        double TVA = Double.parseDouble(JOptionPane.showInputDialog(null, "Entrer la TVA !"));
        
        dtm = (DefaultTableModel) tableCommande.getModel();
        dtm.addRow(new Object[]{
            
            idProduit,
            txtRefProduit,
            txtDesignationProduit,
            txtDescriptifProduit,
            txtPrixUHTProduit,
            qte,
            tot
            
        });
        
        //Calculer le total incluant les frais de port
        for (double i=0; i < tableCommande.getRowCount(); i++) {
            sum = fraisPort + sum+Double.parseDouble((tableCommande.getValueAt((int)i, 6)).toString());
            prixTVA = sum*TVA/100;
            totalTTC = sum + sum*TVA/100;
        }
        
        txtPrixTTCCMd.setText(Double.toString(totalTTC));
        txtQteProduitCMD.setText(Integer.toString(qte));
        txtPrixTHTProduitCMD.setText(Double.toString(tot));
        txtFraisPort.setText(Double.toString(fraisPort));
        txtTVACMD.setText(Double.toString(prixTVA));

        /*txtQteProduitCMD.setText(dtm.getValueAt(selectedIndex, 5).toString());
        txtPrixTHEProduitCMD.setText(dtm.getValueAt(selectedIndex, 6).toString());
        txtPrenomClientProduitCMD.setText(dtm.getValueAt(selectedIndex, 7).toString());
        txtNomClientProduitCMD.setText(dtm.getValueAt(selectedIndex, 8).toString());*/
    }//GEN-LAST:event_tableProduitCommandeMouseClicked

    private void txtPrixTTCCMdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrixTTCCMdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrixTTCCMdActionPerformed

    private void btnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBillActionPerformed
        
        try {
            //Print Bill
            boolean complete = txtBill.print();
            
            if (complete) {
                JOptionPane.showMessageDialog(null, "Impression réussi", "Message", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(null, "Impression en cours", "Imprimante", JOptionPane.ERROR_MESSAGE);
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnPrintBillActionPerformed

    private void btnCreateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBillActionPerformed
        double totalTTC = Double.parseDouble(txtPrixTTCCMd.getText());
        double tva = Double.parseDouble(txtTVACMD.getText());
        double fraisPort = Double.parseDouble(txtFraisPort.getText());
        String prenomClient = txtPrenomCMD.getText();
        String nomClient = txtNomCMD.getText();
        /*String Ref = txtREFProduitCmd.getText();
        String Designation = txtDESIGNATIONProduitCmd.getText();
        String Description = txtDESCRIPTIFProduitCmd.getText();
        String PrixUHT = txtPRIXUHTProduitCmd.getText();
        String QTE = txtQTEProduitCmd.getText();
        String PrixTHT = txtPRIXTHTProduitCmd.getText();*/

        DefaultTableModel model = new DefaultTableModel();

        model = (DefaultTableModel) tableCommande.getModel();

        txtBill.setText(txtBill.getText() + "*************************************************************************************************************\n");
        txtBill.setText(txtBill.getText() + "**********************************          FACTURE XPROD           ****************************************\n");
        txtBill.setText(txtBill.getText() + "*************************************************************************************************************\n");
        //Heading
        txtBill.setText(txtBill.getText() + "REF" + "\t" + "DESIGNATION" + "\t" + "DESCRIPTION" + "\t" + "PRIX UHT" + "\t" + "QTE" + "\t" + "PRIX THT" + "\n");
        //Valeurs
        /*txtBill.setText(txtBill.getText() + Ref + "\t" + Designation + "\t" + Description + "\t" + PrixUHT + "\t" + QTE + "\t" + PrixTHT + "\n");

        txtBill.setText(txtBill.getText() + "\n");

        txtBill.setText(txtBill.getText() + "TotalTTC" + "\t" + totalTTC + " €\n");
        txtBill.setText(txtBill.getText() + "TVA" + "\t" + tva + " €\n");
        txtBill.setText(txtBill.getText() + "Frais de port" + "\t" + fraisPort + " €\n");*/

        for (int i = 0; i < model.getRowCount(); i++) {
            String ref = (String) model.getValueAt(i, 1);
            String designation = (String) model.getValueAt(i, 2);
            String descriptif = (String) model.getValueAt(i, 3);

            Double prixU = (Double) model.getValueAt(i, 4);
            int qte = (int) model.getValueAt(i, 5);
            Double prixtht = (Double) model.getValueAt(i, 6);

            txtBill.setText(txtBill.getText() + ref + "\t" + designation + "\t" + descriptif + "\t" + prixU + "\t" + qte + "\t" + prixtht + "\n");
        }

        txtBill.setText(txtBill.getText() + "\n");
        txtBill.setText(txtBill.getText() + "\n");
        txtBill.setText(txtBill.getText() + "\n");

        txtBill.setText(txtBill.getText() + "\t" + "\t" + "\t" + "\t" + "TVA :" + "\t" + tva + " €\n");
        txtBill.setText(txtBill.getText() + "\t" + "\t" + "\t" + "\t" + "Total TTC :" + "\t" + totalTTC + " €\n");
        txtBill.setText(txtBill.getText() + "\t" + "\t" + "\t" + "\t" + "Frais de port :" + "\t" + fraisPort + " €\n");
        txtBill.setText(txtBill.getText() + "\n");
        txtBill.setText(txtBill.getText() + "*************************************************************************************************************\n");
        txtBill.setText(txtBill.getText() + "                                      MERCI POUR VOTRE VISITE ! À BIENTÔT !\n");

 
    }//GEN-LAST:event_btnCreateBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBill;
    private javax.swing.JButton btnPrintBill;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable tableClients;
    private javax.swing.JTable tableCommande;
    private javax.swing.JTable tableProduitCommande;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtDescriptifProduitCMD;
    private javax.swing.JTextField txtDesignationProduitCMD;
    private javax.swing.JTextField txtFraisPort;
    private javax.swing.JTextField txtNomCMD;
    private javax.swing.JTextField txtPrenomCMD;
    private javax.swing.JTextField txtPrixTHTProduitCMD;
    private javax.swing.JTextField txtPrixTTCCMd;
    private javax.swing.JTextField txtPrixUHTProduitCMD;
    private javax.swing.JTextField txtQteProduitCMD;
    private javax.swing.JTextField txtRefProduitCMD;
    private javax.swing.JTextField txtTVACMD;
    // End of variables declaration//GEN-END:variables
}
